name: Auto Create Timestamp Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate UNIX timestamp (milliseconds)
        id: timestamp
        run: echo "TAG_NAME=$(date +%s%3N)" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.timestamp.outputs.TAG_NAME }}
          git push origin ${{ steps.timestamp.outputs.TAG_NAME }}
